<a href="https://colab.research.google.com/github/Rohanjain1211/UML501_Rohan_Jain_102303740/blob/main/mlassign2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/AWCustomers.csv')
df

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,NaN,Grace,C,Bailey,NaN,6627 Camelback Ct.,NaN,Coronado,California,...,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953,2017-03-06
18357,11459,NaN,Tasha,NaN,Deng,NaN,9627 Kendall Rd,NaN,Port Macquarie,New South Wales,...,Bachelors,Skilled Manual,F,S,0,2,0,0,60992,2017-03-06
18358,12160,NaN,Jaclyn,NaN,Zhang,NaN,4364 Viera Avenue,NaN,Beaverton,Oregon,...,Partial College,Skilled Manual,F,S,0,2,0,0,51859,2017-03-06
18359,14353,NaN,Erin,I,Reed,NaN,3866 Mt. Everest Court,NaN,Vancouver,British Columbia,...,High School,Clerical,F,S,0,0,0,0,87177,2017-03-06
18360,16676,NaN,Amanda,NaN,Perry,NaN,7870 Orangewood Dr.,NaN,Grossmont,California,...,Graduate Degree,Professional,F,M,1,2,0,0,136856,2017-03-06

In [ ]:
df.columns

Index(['CustomerID', 'Title', 'FirstName', 'MiddleName', 'LastName', 'Suffix',
       'AddressLine1', 'AddressLine2', 'City', 'StateProvinceName',
       'CountryRegionName', 'PostalCode', 'PhoneNumber', 'BirthDate',
       'Education', 'Occupation', 'Gender', 'MaritalStatus', 'HomeOwnerFlag',
       'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren',
       'YearlyIncome', 'LastUpdated'],
      dtype='object')

In [ ]:
cols=['CustomerID','MiddleName','CountryRegionName','BirthDate','Occupation','Gender','MaritalStatus','HomeOwnerFlag','NumberCarsOwned','NumberChildrenAtHome','YearlyIncome','LastUpdated']
df1=df[cols]
df1

,CustomerID,MiddleName,CountryRegionName,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,YearlyIncome,LastUpdated
0,21173,C,Australia,1987-11-13,Clerical,M,M,1,3,0,81916,2017-03-06
1,13249,NaN,Canada,1972-07-21,Clerical,M,M,1,2,1,81076,2017-03-06
2,29350,NaN,United States,1985-11-09,Clerical,F,S,0,3,0,86387,2017-03-06
3,13503,NaN,United Kingdom,1977-10-18,Skilled Manual,M,M,1,2,1,61481,2017-03-06
4,22803,J,Germany,1975-02-05,Skilled Manual,M,S,1,1,0,51804,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,C,United States,1990-11-11,Skilled Manual,F,M,0,1,0,52953,2017-03-06
18357,11459,NaN,Australia,1992-10-13,Skilled Manual,F,S,0,2,0,60992,2017-03-06
18358,12160,NaN,United States,1983-11-24,Skilled Manual,F,S,0,2,0,51859,2017-03-06
18359,14353,I,Canada,1995-06-15,Clerical,F,S,0,0,0,87177,2017-03-06
18360,16676,NaN,United States,1986-03-26,Professional,F,M,1,2,0,136856,2017-03-06

In [ ]:
df1['MiddleName']=df1["MiddleName"].fillna('NA')
df1

/tmp/ipython-input-3469294419.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['MiddleName']=df1["MiddleName"].fillna('NA')

,CustomerID,MiddleName,CountryRegionName,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,YearlyIncome,LastUpdated
0,21173,C,Australia,1987-11-13,Clerical,M,M,1,3,0,81916,2017-03-06
1,13249,NA,Canada,1972-07-21,Clerical,M,M,1,2,1,81076,2017-03-06
2,29350,NA,United States,1985-11-09,Clerical,F,S,0,3,0,86387,2017-03-06
3,13503,NA,United Kingdom,1977-10-18,Skilled Manual,M,M,1,2,1,61481,2017-03-06
4,22803,J,Germany,1975-02-05,Skilled Manual,M,S,1,1,0,51804,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,C,United States,1990-11-11,Skilled Manual,F,M,0,1,0,52953,2017-03-06
18357,11459,NA,Australia,1992-10-13,Skilled Manual,F,S,0,2,0,60992,2017-03-06
18358,12160,NA,United States,1983-11-24,Skilled Manual,F,S,0,2,0,51859,2017-03-06
18359,14353,I,Canada,1995-06-15,Clerical,F,S,0,0,0,87177,2017-03-06
18360,16676,NA,United States,1986-03-26,Professional,F,M,1,2,0,136856,2017-03-06

In [ ]:

df1.drop(columns=['CustomerID','MiddleName'],inplace=True,axis=1)
df1

/tmp/ipython-input-3104380307.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(columns=['CustomerID','MiddleName'],inplace=True,axis=1)

,CountryRegionName,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,YearlyIncome
0,Australia,1987-11-13,Clerical,M,M,1,3,0,81916
1,Canada,1972-07-21,Clerical,M,M,1,2,1,81076
2,United States,1985-11-09,Clerical,F,S,0,3,0,86387
3,United Kingdom,1977-10-18,Skilled Manual,M,M,1,2,1,61481
4,Germany,1975-02-05,Skilled Manual,M,S,1,1,0,51804
...,...,...,...,...,...,...,...,...,...
18356,United States,1990-11-11,Skilled Manual,F,M,0,1,0,52953
18357,Australia,1992-10-13,Skilled Manual,F,S,0,2,0,60992
18358,United States,1983-11-24,Skilled Manual,F,S,0,2,0,51859
18359,Canada,1995-06-15,Clerical,F,S,0,0,0,87177
18360,United States,1986-03-26,Professional,F,M,1,2,0,136856

In [ ]:
numeric_cols = ['YearlyIncome', 'NumberCarsOwned', 'NumberChildrenAtHome']

df1['BirthDate'] = pd.to_datetime(df1['BirthDate']).dt.year

df1['Gender'] = df1['Gender'].map({'M': 1, 'F': 0})
df1['MaritalStatus']=df1['MaritalStatus'].map({'M': 1, 'S': 0})

df1

/tmp/ipython-input-3699867290.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['BirthDate'] = pd.to_datetime(df1['BirthDate']).dt.year
/tmp/ipython-input-3699867290.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Gender'] = df1['Gender'].map({'M': 1, 'F': 0})
/tmp/ipython-input-3699867290.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['MaritalStatus']=df1['MaritalStatus'].map({'M': 1, 'S': 0})

,CountryRegionName,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,YearlyIncome
0,Australia,1987,Clerical,1,1,1,3,0,81916
1,Canada,1972,Clerical,1,1,1,2,1,81076
2,United States,1985,Clerical,0,0,0,3,0,86387
3,United Kingdom,1977,Skilled Manual,1,1,1,2,1,61481
4,Germany,1975,Skilled Manual,1,0,1,1,0,51804
...,...,...,...,...,...,...,...,...,...
18356,United States,1990,Skilled Manual,0,1,0,1,0,52953
18357,Australia,1992,Skilled Manual,0,0,0,2,0,60992
18358,United States,1983,Skilled Manual,0,0,0,2,0,51859
18359,Canada,1995,Clerical,0,0,0,0,0,87177
18360,United States,1986,Professional,0,1,1,2,0,136856

In [ ]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler,OneHotEncoder,KBinsDiscretizer
numeric_cols = ['YearlyIncome', 'NumberCarsOwned', 'NumberChildrenAtHome']
scaler=MinMaxScaler()
df1[numeric_cols]=scaler.fit_transform(df1[numeric_cols])
df1

/tmp/ipython-input-1933413651.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[numeric_cols]=scaler.fit_transform(df1[numeric_cols])

,CountryRegionName,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,YearlyIncome
0,Australia,1987,Clerical,1,1,1,0.6,0.000000,0.496842
1,Canada,1972,Clerical,1,1,1,0.4,0.333333,0.489453
2,United States,1985,Clerical,0,0,0,0.6,0.000000,0.536172
3,United Kingdom,1977,Skilled Manual,1,1,1,0.4,0.333333,0.317083
4,Germany,1975,Skilled Manual,1,0,1,0.2,0.000000,0.231958
...,...,...,...,...,...,...,...,...,...
18356,United States,1990,Skilled Manual,0,1,0,0.2,0.000000,0.242065
18357,Australia,1992,Skilled Manual,0,0,0,0.4,0.000000,0.312781
18358,United States,1983,Skilled Manual,0,0,0,0.4,0.000000,0.232442
18359,Canada,1995,Clerical,0,0,0,0.0,0.000000,0.543121
18360,United States,1986,Professional,0,1,1,0.4,0.000000,0.980128

In [ ]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df1['Occupation']=le.fit_transform(df1['Occupation'])
df1

/tmp/ipython-input-1575603679.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Occupation']=le.fit_transform(df1['Occupation'])

,CountryRegionName,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,YearlyIncome
0,Australia,1987,0,1,1,1,0.6,0.000000,0.496842
1,Canada,1972,0,1,1,1,0.4,0.333333,0.489453
2,United States,1985,0,0,0,0,0.6,0.000000,0.536172
3,United Kingdom,1977,4,1,1,1,0.4,0.333333,0.317083
4,Germany,1975,4,1,0,1,0.2,0.000000,0.231958
...,...,...,...,...,...,...,...,...,...
18356,United States,1990,4,0,1,0,0.2,0.000000,0.242065
18357,Australia,1992,4,0,0,0,0.4,0.000000,0.312781
18358,United States,1983,4,0,0,0,0.4,0.000000,0.232442
18359,Canada,1995,0,0,0,0,0.0,0.000000,0.543121
18360,United States,1986,3,0,1,1,0.4,0.000000,0.980128

In [ ]:
ohe=OneHotEncoder()

country_encoded = ohe.fit_transform(df1[['CountryRegionName']]).toarray()

# Create a DataFrame from the one-hot encoded data
country_df = pd.DataFrame(country_encoded, columns=ohe.get_feature_names_out(['CountryRegionName']), index=df1.index)

# Drop the original column and concatenate the new one-hot encoded columns
df1 = df1.drop('CountryRegionName', axis=1).join(country_df)

df1

,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,YearlyIncome,CountryRegionName_Australia,CountryRegionName_Canada,CountryRegionName_France,CountryRegionName_Germany,CountryRegionName_United Kingdom,CountryRegionName_United States
0,1987,0,1,1,1,0.6,0.000000,0.496842,1.0,0.0,0.0,0.0,0.0,0.0
1,1972,0,1,1,1,0.4,0.333333,0.489453,0.0,1.0,0.0,0.0,0.0,0.0
2,1985,0,0,0,0,0.6,0.000000,0.536172,0.0,0.0,0.0,0.0,0.0,1.0
3,1977,4,1,1,1,0.4,0.333333,0.317083,0.0,0.0,0.0,0.0,1.0,0.0
4,1975,4,1,0,1,0.2,0.000000,0.231958,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,1990,4,0,1,0,0.2,0.000000,0.242065,0.0,0.0,0.0,0.0,0.0,1.0
18357,1992,4,0,0,0,0.4,0.000000,0.312781,1.0,0.0,0.0,0.0,0.0,0.0
18358,1983,4,0,0,0,0.4,0.000000,0.232442,0.0,0.0,0.0,0.0,0.0,1.0
18359,1995,0,0,0,0,0.0,0.000000,0.543121,0.0,1.0,0.0,0.0,0.0,0.0
18360,1986,3,0,1,1,0.4,0.000000,0.980128,0.0,0.0,0.0,0.0,0.0,1.0